/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_luajava_luajit_LuaJitNatives */

#ifndef _Included_com_luajava_luajit_LuaJitNatives
#define _Included_com_luajava_luajit_LuaJitNatives
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    reopenGlobal
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_reopenGlobal
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    initBindings
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_initBindings
  (JNIEnv *, jclass);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    getRegistryIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_getRegistryIndex
  (JNIEnv *, jobject);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_checkstack
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1checkstack
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_concat
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1concat
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_createtable
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1createtable
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_equal
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1equal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_error
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1error
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_gc
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1gc
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_getfenv
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1getfenv
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_getfield
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1getfield
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaJ_getfield
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_luaJ_1getfield
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_getglobal
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1getglobal
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaJ_getglobal
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_luaJ_1getglobal
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_getmetatable
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1getmetatable
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_gettable
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1gettable
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaJ_gettable
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_luaJ_1gettable
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_gettop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1gettop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_insert
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1insert
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_isboolean
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1isboolean
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_iscfunction
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1iscfunction
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_isfunction
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1isfunction
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_islightuserdata
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1islightuserdata
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_isnil
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1isnil
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_isnone
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1isnone
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_isnoneornil
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1isnoneornil
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_isnumber
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1isnumber
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_isstring
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1isstring
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_istable
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1istable
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_isthread
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1isthread
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_isuserdata
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1isuserdata
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_lessthan
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1lessthan
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_newtable
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1newtable
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_newthread
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1newthread
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_newuserdata
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1newuserdata
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_next
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1next
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_objlen
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1objlen
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_pcall
 * Signature: (JIII)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1pcall
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_pop
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1pop
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_pushboolean
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1pushboolean
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_pushinteger
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1pushinteger
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_pushlightuserdata
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1pushlightuserdata
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_pushnil
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1pushnil
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_pushnumber
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1pushnumber
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_pushstring
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1pushstring
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaJ_pushstring
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_luaJ_1pushstring
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_pushthread
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1pushthread
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_pushvalue
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1pushvalue
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_rawequal
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1rawequal
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_rawget
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1rawget
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaJ_rawget
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_luaJ_1rawget
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_rawgeti
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1rawgeti
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaJ_rawgeti
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_luaJ_1rawgeti
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_rawset
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1rawset
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_rawseti
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1rawseti
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_remove
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1remove
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_replace
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1replace
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_resume
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1resume
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_setfenv
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1setfenv
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_setfield
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1setfield
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_setglobal
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1setglobal
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_setmetatable
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1setmetatable
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaJ_setmetatable
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_luaJ_1setmetatable
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_settable
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1settable
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_settop
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1settop
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_status
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1status
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_toboolean
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1toboolean
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_tointeger
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1tointeger
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_tonumber
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1tonumber
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_topointer
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1topointer
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_tostring
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1tostring
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_tothread
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1tothread
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_touserdata
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1touserdata
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_type
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1type
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_typename
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1typename
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_xmove
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1xmove
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_yield
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1yield
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_gethookcount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1gethookcount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_gethookmask
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1gethookmask
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_getupvalue
 * Signature: (JII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1getupvalue
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    lua_setupvalue
 * Signature: (JII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_luajava_luajit_LuaJitNatives_lua_1setupvalue
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaL_callmeta
 * Signature: (JILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_luaL_1callmeta
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaL_dostring
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_luaL_1dostring
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaL_getmetafield
 * Signature: (JILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_luaL_1getmetafield
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaL_getmetatable
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_luaL_1getmetatable
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaJ_getmetatable
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_luaJ_1getmetatable
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaL_gsub
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_luajava_luajit_LuaJitNatives_luaL_1gsub
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaL_loadstring
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_luaL_1loadstring
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaL_newmetatable
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_luaL_1newmetatable
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaL_newstate
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_luajava_luajit_LuaJitNatives_luaL_1newstate
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaL_openlibs
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_luaL_1openlibs
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaL_ref
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_luaL_1ref
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaL_typename
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_luajava_luajit_LuaJitNatives_luaL_1typename
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaL_typerror
 * Signature: (JILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_luaL_1typerror
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaL_unref
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_luaL_1unref
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaL_where
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_luaL_1where
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaJ_openlib
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_luaJ_1openlib
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaJ_compare
 * Signature: (JIII)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_luaJ_1compare
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaJ_len
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_luaJ_1len
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaJ_loadbuffer
 * Signature: (JLjava/nio/Buffer;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_luaJ_1loadbuffer
  (JNIEnv *, jobject, jlong, jobject, jint, jstring);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaJ_dobuffer
 * Signature: (JLjava/nio/Buffer;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_luaJ_1dobuffer
  (JNIEnv *, jobject, jlong, jobject, jint, jstring);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaJ_resume
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_luaJ_1resume
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaJ_pushobject
 * Signature: (JLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_luaJ_1pushobject
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaJ_pushclass
 * Signature: (JLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_luaJ_1pushclass
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaJ_pusharray
 * Signature: (JLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_luaJ_1pusharray
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaJ_pushfunction
 * Signature: (JLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_luaJ_1pushfunction
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaJ_isobject
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_luaJ_1isobject
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaJ_toobject
 * Signature: (JI)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_luajava_luajit_LuaJitNatives_luaJ_1toobject
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaJ_newthread
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_luajava_luajit_LuaJitNatives_luaJ_1newthread
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaJ_initloader
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_luaJ_1initloader
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaJ_invokespecial
 * Signature: (JLjava/lang/Class;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_luaJ_1invokespecial
  (JNIEnv *, jobject, jlong, jclass, jstring, jstring, jobject, jstring);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaJ_isinteger
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_luajava_luajit_LuaJitNatives_luaJ_1isinteger
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaJ_removestateindex
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_luaJ_1removestateindex
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaJ_gc
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_luajava_luajit_LuaJitNatives_luaJ_1gc
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaJ_dumptobuffer
 * Signature: (J)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_luajava_luajit_LuaJitNatives_luaJ_1dumptobuffer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaJ_tobuffer
 * Signature: (JI)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_luajava_luajit_LuaJitNatives_luaJ_1tobuffer
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_luajava_luajit_LuaJitNatives
 * Method:    luaJ_todirectbuffer
 * Signature: (JI)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_luajava_luajit_LuaJitNatives_luaJ_1todirectbuffer
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
